module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Events', [{
      userID: 1,
      categoryID: 1,
      title: 'Концерт Ранетки.Возвращение',
      description: 'ищу участника для посещений концерта своей любимой группы',
      location: 'ДК Ленсовета',
      privateSettings: 'public',
      dateTime: '2022-02-13',
      photo: 'http://localhost:4000/images/eventsPhotoSeed/86ff424.jpeg',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      userID: 2,
      categoryID: 2,
      title: 'Поездка в репино',
      description: 'Kто со мной?',
      location: 'Репино',
      privateSettings: 'public',
      dateTime: '2022-02-14',
      photo: 'http://localhost:4000/images/eventsPhotoSeed/Repino-Honka-web.jpeg',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      userID: 3,
      categoryID: 3,
      title: 'Сходить в кино',
      description: 'пойду в кино один',
      location: 'Каро на Лиговском',
      privateSettings: 'public',
      dateTime: '2022-02-15',
      photo: 'http://localhost:4000/images/eventsPhotoSeed/GL(188842).jpeg',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      userID: 4,
      categoryID: 4,
      title: 'Поход в баню',
      description: 'Хочу пойти в баню, в которой Балабанов снимал филь "Я тоже хочу"',
      location: 'ДК Ленсовета',
      privateSettings: 'public',
      photo: 'http://localhost:4000/images/eventsPhotoSeed/1-5.jpeg',
      dateTime: '2022-02-16',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      userID: 5,
      categoryID: 5,
      title: 'Поход в кальян',
      description: 'Пошлите',
      location: ' "Феромон" на Подъяческой',
      privateSettings: 'public',
      dateTime: '2022-02-17',
      photo: 'http://localhost:4000/images/eventsPhotoSeed/chilling-moscow-main-752x440.jpeg',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      userID: 6,
      categoryID: 6,
      title: 'Пробежка в парке',
      description: 'Попытка начать здоровый образ жизни',
      location: 'в центре',
      privateSettings: 'public',
      dateTime: '2022-02-18',
      photo: 'http://localhost:4000/images/eventsPhotoSeed/scale_1200.jpeg',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Events', null, {});
  },
};
