module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Users', [{
      username: 'alla',
      name: 'Алла',
      lastName: 'Борисова',
      email: 'alla@borisova.ru',
      city: 'Санкт-Петербург',
      password: '123456',
      phoneNumber: '89213356535',
      photo: 'http://localhost:4000/images/userPhotoSeed/1QpLdtkgINU.jpeg',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      username: 'galina',
      name: 'Галина',
      lastName: 'Андреева',
      email: 'galina@andreeva.ru',
      city: 'Санкт-Петербург',
      password: '123456',
      photo: 'http://localhost:4000/images/userPhotoSeed/804572.150x225.jpeg',
      phoneNumber: '89213356535',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      username: 'andrey',
      name: 'Андрей',
      lastName: 'Галинович',
      email: 'andrey@galinovich.ru',
      city: 'Санкт-Петербург',
      password: '123456',
      photo: 'http://localhost:4000/images/userPhotoSeed/5869c01f-76d.jpeg',
      phoneNumber: '89213356535',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      username: 'artem',
      name: 'Артем',
      lastName: 'Алексеев',
      email: 'artem@alekseev.ru',
      city: 'Москва',
      password: '123456',
      photo: 'http://localhost:4000/images/userPhotoSeed/649586.jpeg',
      phoneNumber: '89213356535',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      username: 'marfa',
      name: 'Марфа',
      lastName: 'Филлипова',
      email: 'marfa@fillipova.ru',
      city: 'Москва',
      password: '123456',
      photo: 'http://localhost:4000/images/userPhotoSeed/d842ee939e3dce58515cc22b3fe3b2f3.jpeg',
      phoneNumber: '89213356535',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      username: 'frosya',
      name: 'Ефросинья',
      lastName: 'Федорова',
      email: 'frosya@fedorova.ru',
      city: 'Москва',
      password: '123456',
      phoneNumber: '89213356535',
      photo: 'http://localhost:4000/images/userPhotoSeed/1531929349_1531929344_r9f7sp_att-url-download.jpeg',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
