export const PUBLIC_EVENTS_FETCH = 'PUBLIC_EVENTS_FETCH';
export const INIT_PUBLIC_EVENTS = 'INIT_PUBLIC_EVENTS';
export const INIT_USERS_EVENTS = 'INIT_USERS_EVENTS';
export const INIT_USERS_EVENTS_FETCH = 'INIT_USERS_EVENTS_FETCH';
export const FETCH_POST_EVENT = 'FETCH_POST_EVENT';
export const INIT_EVENTS_FETCH = 'INIT_EVENTS_FETCH'
