export const INIT_FRIENDS = 'INIT_FRIENDS';
export const INIT_FRIENDS_ASYNC = 'INIT_FRIENDS_ASYNC';
export const ADD_FRIENDSHIP = 'ADD_FRIENDSHIP';
export const ADD_FRIENDSHIP_FETCH = "ADD_FRIENDSHIP_FETCH";
