export const INIT_FRIENDS = 'INIT_FRIENDS';
export const INIT_FRIENDS_ASYNC = 'INIT_FRIENDS_ASYNC';
export const ADD_FRIENDSHIP = 'ADD_FRIENDSHIP';
export const ADD_FRIENDSHIP_FETCH = "ADD_FRIENDSHIP_FETCH";
export const INIT_FRIENDS_REQUEST_NOTIFICATIONS = 'INIT_FRIENDS_REQUEST_NOTIFICATIONS'
export const INIT_FRIENDS_REQUEST_NOTIFICATIONS_ASYNC = 'INIT_FRIENDS_REQUEST_NOTIFICATIONS_ASYNC'
export const ACCEPT_FRIENDSHIP='ACCEPT_FRIENDSHIP'
export const ACCEPT_FRIENDSHIP_ASYNC ='ACCEPT_FRIENDSHIP_ASYNC';
export const REJECT_FRIENDSHIP = 'REJECT_FRIENDSHIP'
export const REJECT_FRIENDSHIP_ASYNC = 'REJECT_FRIENDSHIP_ASYNC';
export const DELETE_FRIENDSHIP_FETCH = 'DELETE_FRIENDSHIP_FETCH';
export const DELETE_FRIENDSHIP = 'DELETE_FRIENDSHIP';

