export const REGISTRATION_FETCH = 'REGISTRATION_FETCH';
export const ADD_USER = 'ADD_USER';
export const LOGIN_FETCH = 'LOGIN_FETCH';
export const GLOBAL_LOGIN_FETCH = 'GLOBAL_LOGIN_FETCH';
export const INIT_USER = 'INIT_USER';
export const LOGOUT_FETCH = 'LOGOUT_FETCH';
export const DELETE_USER = 'DELETE_USER';
export const INIT_USERSLIST_FETCH = 'INIT_USERSLIST_FETCH';
export const INIT_USERSLIST = 'INIT_USERSLIST';
export const INIT_ANOTHER_USER_FETCH = 'INIT_ANOTHER_USER_FETCH ';
export const INIT_ANOTHER_USER_EVENTS_FETCH = 'INIT_ANOTHER_USER_EVENTS_FETCH ';
export const INIT_ANOTHER_USER = 'INIT_ANOTHER_USER';
export const INIT_ANOTHER_USER_EVENTS = 'INIT_ANOTHER_USER_EVENTS';
export const SAVE_AVATAR = 'SAVE_AVATAR';
export const SAVE_AVATAR_FETCH = 'SAVE_AVATAR_FETCH';
export const CLEAN_USERLIST = 'CLEAN_USERLIST'

export const NEW_MESSAGE = 'NEW_MESSAGE'

