export const REGISTRATION_FETCH = 'REGISTRATION_FETCH';
export const ADD_USER = 'ADD_USER';
export const LOGIN_FETCH = 'LOGIN_FETCH';
export const INIT_USER = 'INIT_USER';
export const LOGOUT_FETCH = 'LOGOUT_FETCH';
export const DELETE_USER = 'DELETE_USER';
export const INIT_USERSLIST_FETCH = 'INIT_USERSLIST_FETCH';
export const INIT_USERSLIST = 'INIT_USERSLIST';

